# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('Applicant_Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('DateOfBirth', models.DateField()),
                ('Qualification', models.CharField(max_length=50)),
                ('Experience', models.IntegerField()),
                ('ExpectedSalary', models.IntegerField()),
                ('Languages', models.CharField(max_length=30)),
                ('Verified_By', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('City_Id', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployerName', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Applicant_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillApp.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('JobRole_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Jobtype', models.CharField(max_length=30)),
                ('IndustryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstitutionName', models.CharField(max_length=50)),
                ('EducationLevel', models.CharField(max_length=10)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillApp.City'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillApp.JobRole'),
        ),
    ]
